server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: NotebookAPIClient
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/notebook
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#    ratelimiters:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    health:
#      show-details: always
#    info:
#      show-details: always
#
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 3
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 3
#        waitDurationInOpenState: 3000
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        slidingWindowType: COUNT_BASED


custom:
  notesPath: http://localhost:8081/api/v1/notes
  notesPathWithId: http://localhost:8081/api/v1/notes/{id}
  authPath: http://localhost:8999/api/v1/auth/authentication
  secret: fe623bd733fc57bad3fe78db92b1016488e323912553695449d0d39cb833b13a

logging:
  level:
    org:
      springframework:
        security: WARN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost