server:
  port: 8999

logging:
  level:
    org:
      springframework:
        security: INFO

myapp:
  rootUrl: http://localhost:8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka