server:
  port: 8999

spring:
  application:
    name: Auth-Server

logging:
  level:
    org:
      springframework:
        security: INFO

custom:
  fetchUserUri: http://localhost:8080/api/v1/user/email/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
