server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
#  main:
#    web-application-type: reactive
  application:
    name: NotebookUserRegistrationServer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/notebook_users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    gateway:
#      default-filters:
#        - TokenRelay=
#      routes:
#        - id: route
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/**


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka