server:
  port: 8084

spring:
  application:
    name: MailingService
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: notebookmailer
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

logging:
  file:
    name: ./logs/mailer-log.log
  logback:
    rollingpolicy:
      file-name-pattern: email-log-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka